[build]
  command = "npm --prefix apps/website run build"
  publish = "apps/website/dist"

[[redirects]]
  from = "/api/*"
  to = "https://api.faako.nanaabaackah.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
